#pragma once
#ifndef OPENGM_PYTHON_OPENGM_PYTHON_VERSION_PATCH_HPP
#define OPENGM_PYTHON_OPENGM_PYTHON_VERSION_PATCH_HPP



#define OPENGM_PYTHON_VERSION_PATCH 0

namespace opengm {


} // end namespace opengm


#endif // OPENGM_PYTHON_OPENGM_PYTHON_VERSION_PATCH_HPP