#pragma once
#ifndef OPENGM_PYTHON_OPENGM_PYTHON_VERSION_MINOR_HPP
#define OPENGM_PYTHON_OPENGM_PYTHON_VERSION_MINOR_HPP

#define OPENGM_PYTHON_VERSION_MINOR 1


namespace opengm {


} // end namespace opengm


#endif // OPENGM_PYTHON_OPENGM_PYTHON_VERSION_MINOR_HPP